variables:
  GIT_SUBMODULE_STRATEGY: normal

stages:
  - bootstrap
  - build

#
# The main Fabrique build uses Fabrique. This requires a bootstrapping step.
#
bootstrap:make:
  stage: bootstrap
  script:
    - cd bootstrap
    - ./gen --format=make build
    - make -C build

  artifacts: {paths: ["bootstrap/build"]}

bootstrap:ninja:
  stage: bootstrap
  before_script: [apt update && apt install -y ninja-build]
  script:
    - cd bootstrap
    - ./gen --format=ninja build
    - ninja -C build

  artifacts: {paths: ["bootstrap/build"]}

#
# Build Fabrique using Fabrique.
#
.build_template: &build
  stage: build
  artifacts:
    paths:
      - bin/fab
      - lib/*.so
      - lib/fabrique/*.so

build:make:clang:
  <<: *build
  dependencies: ["bootstrap:make"]
  before_script: [apt update && apt install -y clang]
  script:
    - ./bootstrap/build/bin/fab --output=build --format=gmake
    - make -C build everything

build:make:gcc:
  <<: *build
  dependencies: ["bootstrap:make"]
  script:
    - ./bootstrap/build/bin/fab --output=build --format=gmake -D gcc=true
    - make -C build everything

build:ninja:clang:
  <<: *build
  dependencies: ["bootstrap:ninja"]
  before_script: [apt update && apt install -y clang ninja-build]
  script:
    - ./bootstrap/build/bin/fab --output=build --format=ninja ..
    - ninja -C build everything

build:ninja:gcc:
  <<: *build
  dependencies: ["bootstrap:ninja"]
  before_script: [apt update && apt install -y ninja-build]
  script:
    - ./bootstrap/build/bin/fab --output=build --format=ninja -D gcc=true ..
    - ninja -C build everything
