#!/bin/sh

# Re-build the GNUmakefile
./regenerate.sh

# Manually create this one directory until we can properly fix the make backend...
mkdir -p lib/fabrique

# What is the GNU Make binary called on this platform?
if [ "`which gmake`" != "" ]
then
	MAKE=gmake
else
	MAKE=make
fi

$MAKE $* everything || exit 1
